// <auto-generated />
using BlindVacationFullstack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BlindVacationFullstack.Migrations
{
    [DbContext(typeof(VacationMVCDbContext))]
    [Migration("20201013054639_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BlindVacationFullstack.Models.PopularTrip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AnswerCode")
                        .HasColumnType("text");

                    b.Property<string>("CityName")
                        .HasColumnType("text");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("boolean");

                    b.Property<bool>("InUSA")
                        .HasColumnType("boolean");

                    b.Property<bool>("LikesHot")
                        .HasColumnType("boolean");

                    b.Property<bool>("LikesOutdoor")
                        .HasColumnType("boolean");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("VacationName")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("PopularTrips");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnswerCode = "0,1,2,0,1",
                            CityName = "Seoul, South Korea",
                            HasChildren = false,
                            InUSA = false,
                            LikesHot = true,
                            LikesOutdoor = true,
                            Popularity = 3,
                            Price = 2,
                            VacationName = "Korea Vacation 2020"
                        },
                        new
                        {
                            ID = 2,
                            AnswerCode = "0,0,2,0,0",
                            CityName = "Moscow, Russia",
                            HasChildren = false,
                            InUSA = false,
                            LikesHot = false,
                            LikesOutdoor = false,
                            Popularity = 69,
                            Price = 2,
                            VacationName = "Bring a coat!!"
                        });
                });

            modelBuilder.Entity("BlindVacationFullstack.Models.SavedTrip", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<string>("AnswerCode")
                        .HasColumnType("text");

                    b.Property<string>("CityName")
                        .HasColumnType("text");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("boolean");

                    b.Property<bool>("InUSA")
                        .HasColumnType("boolean");

                    b.Property<bool>("LikesHot")
                        .HasColumnType("boolean");

                    b.Property<bool>("LikesOutdoor")
                        .HasColumnType("boolean");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("VacationName")
                        .HasColumnType("text");

                    b.HasKey("UserID", "AnswerCode");

                    b.ToTable("SavedTrips");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AnswerCode = "0,1,3,0,0",
                            CityName = "Paris, France",
                            HasChildren = false,
                            InUSA = false,
                            LikesHot = true,
                            LikesOutdoor = false,
                            Price = 3,
                            VacationName = "We need baguettes really badly."
                        });
                });

            modelBuilder.Entity("BlindVacationFullstack.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FaveTripItem")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FaveTripItem = 2,
                            Name = "Kyungrae"
                        },
                        new
                        {
                            ID = 2,
                            FaveTripItem = 16,
                            Name = "Karina"
                        },
                        new
                        {
                            ID = 3,
                            FaveTripItem = 12,
                            Name = "Biniam"
                        },
                        new
                        {
                            ID = 4,
                            FaveTripItem = 15,
                            Name = "Enrique"
                        },
                        new
                        {
                            ID = 5,
                            FaveTripItem = 10,
                            Name = "Chris"
                        });
                });

            modelBuilder.Entity("BlindVacationFullstack.Models.SavedTrip", b =>
                {
                    b.HasOne("BlindVacationFullstack.Models.User", "User")
                        .WithMany("SavedTrips")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
