// <auto-generated />
using BlindVacationFullstack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlindVacationFullstack.Migrations
{
    [DbContext(typeof(VacationMVCDbContext))]
    partial class VacationMVCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlindVacationFullstack.Models.PopularTrip", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnswerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("InUSA")
                        .HasColumnType("bit");

                    b.Property<bool>("LikesHot")
                        .HasColumnType("bit");

                    b.Property<bool>("LikesOutdoor")
                        .HasColumnType("bit");

                    b.Property<int>("Popularity")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("VacationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PopularTrips");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnswerCode = "0,1,1,0,1",
                            CityName = "North Korea",
                            HasChildren = false,
                            InUSA = false,
                            LikesHot = true,
                            LikesOutdoor = true,
                            Popularity = 3,
                            Price = 1,
                            VacationName = "Chris baptism party"
                        },
                        new
                        {
                            ID = 2,
                            AnswerCode = "0,1,3,0,0",
                            CityName = "Paris",
                            HasChildren = false,
                            InUSA = false,
                            LikesHot = true,
                            LikesOutdoor = false,
                            Popularity = 69,
                            Price = 3,
                            VacationName = "Chris Refugee party"
                        });
                });

            modelBuilder.Entity("BlindVacationFullstack.Models.SavedTrip", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("AnswerCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("bit");

                    b.Property<bool>("InUSA")
                        .HasColumnType("bit");

                    b.Property<bool>("LikesHot")
                        .HasColumnType("bit");

                    b.Property<bool>("LikesOutdoor")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("VacationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID", "AnswerCode");

                    b.ToTable("SavedTrips");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AnswerCode = "0,1,1,0,1",
                            CityName = "Tunisia",
                            HasChildren = false,
                            InUSA = false,
                            LikesHot = true,
                            LikesOutdoor = true,
                            Price = 1,
                            VacationName = "Chris bachelor party"
                        },
                        new
                        {
                            UserID = 1,
                            AnswerCode = "0,1,3,0,0",
                            CityName = "Paris",
                            HasChildren = false,
                            InUSA = false,
                            LikesHot = true,
                            LikesOutdoor = false,
                            Price = 3,
                            VacationName = "Chris divorce party"
                        });
                });

            modelBuilder.Entity("BlindVacationFullstack.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FaveTripItem")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FaveTripItem = 2,
                            Name = "Kyungrae"
                        },
                        new
                        {
                            ID = 2,
                            FaveTripItem = 16,
                            Name = "Karina"
                        },
                        new
                        {
                            ID = 3,
                            FaveTripItem = 12,
                            Name = "Biniam"
                        },
                        new
                        {
                            ID = 4,
                            FaveTripItem = 15,
                            Name = "Enrique"
                        },
                        new
                        {
                            ID = 5,
                            FaveTripItem = 10,
                            Name = "Chris"
                        });
                });

            modelBuilder.Entity("BlindVacationFullstack.Models.SavedTrip", b =>
                {
                    b.HasOne("BlindVacationFullstack.Models.User", "User")
                        .WithMany("SavedTrips")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
